import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Lora, Inter } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
});

const lora = Lora ({
  subsets : ["latin"],
  weight: ['400', '700'],
  variable : '--font-lora'
})

const inter = Inter ({
  subsets : ['latin'],
  weight: ['400', '700'],
  variable : "--font-inter"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${lora.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
